// Domyślne 19 wspólnot mapy świata (seed). Teksty (name/cc/tag/note) są edytowalne
// w Personal OS; współrzędne i grupa (grp) są strukturalne (bazowe też w kodzie strony).
export interface CommunitySeed {
  key: string;
  name: string;
  ccPl: string;
  ccEn: string;
  tagPl: string;
  tagEn: string;
  notePl: string;
  noteEn: string;
  lat: number;
  lng: number;
  grp: string;
  order: number;
}

export const COMMUNITY_SEED: CommunitySeed[] = [
  { key: 'warszawa', name: 'Warszawa', ccPl: 'Polska', ccEn: 'Poland', lat: 52.23, lng: 21.01, grp: 'hub', order: 0, tagPl: 'Europa', tagEn: 'Europe', notePl: 'Wspólnota warszawska ICPE Mission — ludzie świeccy, którzy pośród pracy i codzienności żyją wiarą razem. Spotykamy się na modlitwie, formacji i otwartych wieczorach uwielbienia. To z perspektywy Warszawy powstała ta strona.', noteEn: 'The Warsaw ICPE Mission community — lay people who live their faith together in the middle of work and everyday life. We gather for prayer, formation and open worship evenings. This site is told from Warsaw.' },
  { key: 'krakow', name: 'Kraków', ccPl: 'Polska', ccEn: 'Poland', lat: 50.06, lng: 19.94, grp: 'pl', order: 1, tagPl: 'Europa', tagEn: 'Europe', notePl: 'Krakowska wspólnota ICPE Mission. Grupa świeckich zaangażowanych w ewangelizację, wspólną modlitwę i codzienne życie wiarą w sercu Małopolski.', noteEn: 'The Kraków ICPE Mission community. Lay people engaged in evangelisation, shared prayer and everyday life of faith in the heart of Lesser Poland.' },
  { key: 'lublin', name: 'Lublin', ccPl: 'Polska · 2 wspólnoty', ccEn: 'Poland · 2 communities', lat: 51.25, lng: 22.57, grp: 'pl', order: 2, tagPl: 'Europa', tagEn: 'Europe', notePl: 'Dwie wspólnoty ICPE Mission w Lublinie — dwa domy jednej rodziny. Żyją modlitwą, formacją i posługą, dzieląc się wiarą we wschodniej Polsce.', noteEn: 'Two ICPE Mission communities in Lublin — two homes of one family. They live by prayer, formation and service, sharing faith in eastern Poland.' },
  { key: 'malta', name: 'Malta', ccPl: 'Malta · dom macierzysty', ccEn: 'Malta · motherhouse', lat: 35.90, lng: 14.51, grp: 'hq', order: 3, tagPl: 'Europa', tagEn: 'Europe', notePl: 'Dom macierzysty wspólnoty. To tutaj w 1985 roku Mario i Anna Cappello wraz z grupą świeckich założyli Instytut Ewangelizacji Świata. Malta pozostaje sercem międzynarodowej rodziny ICPE.', noteEn: 'The motherhouse of the community. Here, in 1985, Mario and Anna Cappello together with a group of lay people founded the Institute for World Evangelisation. Malta remains the heart of the international ICPE family.' },
  { key: 'fraternia', name: 'Fraternia kapłanów', ccPl: 'Malta', ccEn: 'Malta', lat: 35.88, lng: 14.62, grp: 'hq', order: 4, tagPl: 'Europa', tagEn: 'Europe', notePl: 'Fraternia kapłanów ICPE Mission z siedzibą na Malcie. Kapłani, którzy towarzyszą świeckim wspólnotom na całym świecie — w formacji, sakramentach i wspólnej misji.', noteEn: 'The Fraternity of ICPE Mission priests, based in Malta. Priests who accompany the lay communities around the world — in formation, the sacraments and a shared mission.' },
  { key: 'oregon', name: 'Oregon', ccPl: 'USA', ccEn: 'USA', lat: 44.9, lng: -122.8, grp: 'world', order: 5, tagPl: 'Ameryka Płn.', tagEn: 'North America', notePl: 'Szkoła Świadectwa (School of Witness) w Oregonie. Miesięczna, w pełni stacjonarna szkoła formacji: modlitwa, życie we wspólnocie, studium i ewangelizacja, prowadząca do stania się świadkiem wiary.', noteEn: 'The School of Witness in Oregon. A month-long, fully residential school of formation: prayer, community life, study and outreach, leading participants to become witnesses of the faith.' },
  { key: 'seul', name: 'Seul', ccPl: 'Korea Płd.', ccEn: 'South Korea', lat: 37.57, lng: 126.98, grp: 'world', order: 6, tagPl: 'Azja', tagEn: 'Asia', notePl: 'Wspólnota ICPE Mission w Korei Południowej. Świeccy misjonarze niosący Ewangelię w dynamicznym, wielkomiejskim kontekście azjatyckim.', noteEn: 'The ICPE Mission community in South Korea. Lay missionaries bringing the Gospel into a fast-moving, urban Asian context.' },
  { key: 'singapur', name: 'Singapur', ccPl: 'Singapur', ccEn: 'Singapore', lat: 1.35, lng: 103.82, grp: 'world', order: 7, tagPl: 'Azja', tagEn: 'Asia', notePl: 'Earthen Vessels Catholic Community — wspólnota ICPE Mission założona w 1996 roku jako grupa młodych dorosłych. Prowadzi rekolekcje i programy formacyjne, żyjąc słowami „skarb w naczyniach glinianych".', noteEn: 'Earthen Vessels Catholic Community — an ICPE Mission community founded in 1996 as a group of young adults. It runs retreats and formation programmes, living out the words “treasure in earthen vessels”.' },
  { key: 'manila', name: 'Manila', ccPl: 'Filipiny', ccEn: 'Philippines', lat: 14.60, lng: 120.98, grp: 'world', order: 8, tagPl: 'Azja', tagEn: 'Asia', notePl: 'Wspólnota ICPE Mission na Filipinach — w kraju o żywej, ludowej wierze, gdzie ewangelizacja prowadzona przez świeckich ma szczególną siłę.', noteEn: 'The ICPE Mission community in the Philippines — a country of vibrant, popular faith where lay-led evangelisation has a special strength.' },
  { key: 'wellington', name: 'Wellington', ccPl: 'Nowa Zelandia', ccEn: 'New Zealand', lat: -41.29, lng: 174.78, grp: 'world', order: 9, tagPl: 'Oceania', tagEn: 'Oceania', notePl: 'Wspólnota ICPE Mission w Nowej Zelandii — mały, ale gorliwy dom rodziny ICPE niemal na krańcu świata.', noteEn: 'The ICPE Mission community in New Zealand — a small but fervent home of the ICPE family, near the end of the world.' },
  { key: 'kuala-lumpur', name: 'Kuala Lumpur', ccPl: 'Malezja', ccEn: 'Malaysia', lat: 3.14, lng: 101.69, grp: 'world', order: 10, tagPl: 'Azja', tagEn: 'Asia', notePl: 'Wspólnota ICPE Mission w Kuala Lumpur. Świadectwo chrześcijańskiej wspólnoty w wielokulturowej, wieloreligijnej Malezji.', noteEn: 'The ICPE Mission community in Kuala Lumpur. A witness of Christian community in multicultural, multi-religious Malaysia.' },
  { key: 'kota-kinabalu', name: 'Kota Kinabalu', ccPl: 'Malezja', ccEn: 'Malaysia', lat: 5.98, lng: 116.07, grp: 'world', order: 11, tagPl: 'Azja', tagEn: 'Asia', notePl: 'Wspólnota ICPE Mission w Kota Kinabalu na Borneo. Drugi malezyjski dom rodziny, we wschodniej części kraju.', noteEn: 'The ICPE Mission community in Kota Kinabalu on Borneo. The family’s second Malaysian home, in the east of the country.' },
  { key: 'partinico', name: 'Partinico', ccPl: 'Włochy · Sycylia', ccEn: 'Italy · Sicily', lat: 38.05, lng: 13.12, grp: 'world', order: 12, tagPl: 'Europa', tagEn: 'Europe', notePl: 'Wspólnota ICPE Mission na Sycylii, w Partinico koło Palermo. Śródziemnomorski dom modlitwy i ewangelizacji.', noteEn: 'The ICPE Mission community in Sicily, in Partinico near Palermo. A Mediterranean home of prayer and evangelisation.' },
  { key: 'mysore', name: 'Mysore', ccPl: 'Indie', ccEn: 'India', lat: 12.30, lng: 76.64, grp: 'world', order: 13, tagPl: 'Azja', tagEn: 'Asia', notePl: 'Wspólnota ICPE Mission w Mysore. Jeden z indyjskich ośrodków formacji, z których wyrosło wielu świeckich ewangelizatorów.', noteEn: 'The ICPE Mission community in Mysore. One of the Indian centres of formation from which many lay evangelisers have grown.' },
  { key: 'bangalore', name: 'Bangalore', ccPl: 'Indie', ccEn: 'India', lat: 12.97, lng: 77.59, grp: 'world', order: 14, tagPl: 'Azja', tagEn: 'Asia', notePl: 'Wspólnota ICPE Mission w Bangalore. Dom rodziny ICPE w dynamicznym, młodym mieście południowych Indii.', noteEn: 'The ICPE Mission community in Bangalore. A home of the ICPE family in a dynamic, young city of southern India.' },
  { key: 'kumasi', name: 'Kumasi', ccPl: 'Ghana', ccEn: 'Ghana', lat: 6.69, lng: -1.62, grp: 'world', order: 15, tagPl: 'Afryka', tagEn: 'Africa', notePl: 'Szkoła Ewangelizacji ICPE Mission w Kumasi. Jeden z afrykańskich ośrodków formacji świeckich, którzy niosą Ewangelię z wielką radością.', noteEn: 'The ICPE Mission School of Evangelisation in Kumasi. One of the African centres forming lay people who carry the Gospel with great joy.' },
  { key: 'mannheim', name: 'Mannheim', ccPl: 'Niemcy', ccEn: 'Germany', lat: 49.49, lng: 8.47, grp: 'world', order: 16, tagPl: 'Europa', tagEn: 'Europe', notePl: 'Wspólnota ICPE Mission w Mannheim. Europejski dom rodziny, świadczący o wierze w zsekularyzowanym kontekście Niemiec.', noteEn: 'The ICPE Mission community in Mannheim. A European home of the family, witnessing to faith in Germany’s secular context.' },
  { key: 'bogota', name: 'Bogotá', ccPl: 'Kolumbia', ccEn: 'Colombia', lat: 4.71, lng: -74.07, grp: 'world', order: 17, tagPl: 'Ameryka Płd.', tagEn: 'South America', notePl: 'Wspólnota ICPE Mission w Kolumbii. Latynoamerykański dom rodziny, pełen żywej, wyrazistej wiary.', noteEn: 'The ICPE Mission community in Colombia. A Latin American home of the family, full of vivid, expressive faith.' },
  { key: 'sydney', name: 'Sydney', ccPl: 'Australia', ccEn: 'Australia', lat: -33.87, lng: 151.21, grp: 'world', order: 18, tagPl: 'Oceania', tagEn: 'Oceania', notePl: 'Wspólnota ICPE Mission w Sydney. Dom rodziny ICPE na antypodach, w wielokulturowej Australii.', noteEn: 'The ICPE Mission community in Sydney. A home of the ICPE family at the antipodes, in multicultural Australia.' },
];
